# Generated by Django 4.2.6 on 2023-12-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=255)),
                ('sender_type', models.CharField(choices=[('User', 'User'), ('System', 'System'), ('Service_Provider', 'Service_Provider')], max_length=32)),
                ('receiver', models.CharField(max_length=255)),
                ('receiver_type', models.CharField(choices=[('User', 'User'), ('System', 'System'), ('Service_Provider', 'Service_Provider')], max_length=32)),
                ('read', models.BooleanField(default=False)),
                ('ar_content', models.CharField(max_length=1023)),
                ('en_content', models.CharField(max_length=1023)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
