# Generated by Django 4.2.6 on 2023-12-09 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service_providers', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ar_title', models.CharField(max_length=127)),
                ('en_title', models.CharField(max_length=127)),
                ('ar_description', models.TextField()),
                ('en_description', models.TextField()),
                ('image', models.CharField(max_length=256)),
                ('price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='category.category')),
                ('provider_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='service_providers.serviceproviderlocations')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.SmallIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_rates', to='services.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_services_rates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='servicerates',
            constraint=models.UniqueConstraint(fields=('user', 'service'), name='user_service_constraint'),
        ),
    ]
