# Generated by Django 4.2.6 on 2024-01-10 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_discount_ammount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['id']},
        ),
    ]
