# Generated by Django 4.2.6 on 2024-01-13 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=127)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('read_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contact_us', to='users.admins')),
            ],
        ),
    ]
