# Generated by Django 4.2.6 on 2023-12-09 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service_providers', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('ar_title', models.CharField(max_length=128)),
                ('en_title', models.CharField(max_length=128)),
                ('ar_description', models.TextField()),
                ('en_description', models.TextField()),
                ('images', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('service_provider_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_providers.serviceproviderlocations')),
            ],
        ),
        migrations.CreateModel(
            name='ProductRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.SmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_rates', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='productrates',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='user_product_constraint'),
        ),
    ]
