# Generated by Django 4.2.6 on 2024-01-10 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_discount_ammount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
    ]
